// SharePointStaging — shared base query (set Enable Load = OFF)
// Parses the SharePoint NDJSON once, one row per audit record, keeping the raw
// top-level record so each child query can expand only what it needs.
let
    Source = AzureStorage.DataLake("https://" & DataLakeAccountName & ".dfs.core.windows.net/auditlogs/sharepoint-json"),
    Files  = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    Cutoff = Date.AddDays(Date.From(DateTime.LocalNow()), - LoadDays),
    Recent = Table.SelectRows(Files, each
        let
            after = Text.AfterDelimiter([Folder Path], "-json/"),
            segs  = List.Select(Text.Split(after, "/"), each _ <> ""),
            y     = try Number.From(segs{0}) otherwise null,
            m     = try Number.From(segs{1}) otherwise null,
            d     = try Number.From(segs{2}) otherwise null,
            pdate = if y = null or m = null or d = null then null else (try #date(y, m, d) otherwise null)
        in  pdate <> null and pdate >= Cutoff),
    Parsed = Table.AddColumn(Recent, "Records", each
        let
            lines    = Lines.FromBinary([Content], null, null, 65001),   // 65001 = UTF-8
            nonEmpty = List.Select(lines, each Text.Trim(_) <> ""),
            recs     = List.Transform(nonEmpty, each Json.Document(_))
        in  recs),
    Kept   = Table.SelectColumns(Parsed, {"Name", "Records"}),
    ToRows = Table.ExpandListColumn(Kept, "Records"),
    NoNull = Table.SelectRows(ToRows, each [Records] <> null),
    WithId = Table.AddColumn(NoNull, "EventId", each Record.FieldOrDefault([Records], "Id"), type text),
    Result = Table.RenameColumns(WithId, {{"Name", "SourceFile"}, {"Records", "Record"}})
in
    Result
